// ── Curated category packs (50+ drawable words each) ─────────────────────
// Every word must exist in the emoji-art pool (wordArt.js ∩ dictionary) to be
// usable in system rounds. server.js filters each list at merge time and the
// integration test asserts every category keeps ≥50 drawable words.

const PACKS = {
  animals: 'animal ant hill bee hive beast bull dog cattle chick dinosaur dragon eagle elephant fire fly flamingo goldfish honey bee horse insect kangaroo lady bug monkey mosquito mouse night owl pig pen robin scorpion sea horse seahorse shark sheep snake squirrel star fish starfish tiger tortoise badger beaver buffalo bunny cobra coyote crane falcon ferret gazelle gecko gibbon gopher heron hippo hyena iguana jaguar lemur leopard llama lobster manatee otter panda panther pelican piranha platypus puffin python rabbit raven rhino seagull skunk sloth sparrow stork tadpole tapir toucan trout viper vulture walrus weasel whale wombat zebra beetle lizard spider turtle dolphin octopus'.split(/\s+/),
  food: 'apple banana orange lemon grape cherry berry strawberry blueberry watermelon melon peach pear plum mango pineapple coconut kiwi avocado tomato potato carrot onion garlic pepper corn pea bean rice bread cake pie cookie donut muffin croissant bagel pizza burger hotdog sandwich taco pasta noodle cheese butter egg bacon ham sausage fish shrimp sushi salad soup honey milk coffee tea juice water chocolate candy lollipop popcorn icecream fries almond apricot biscuit broccoli caramel celery chili clove cranberry cucumber custard dough dumpling eggplant fennel flour ginger granola guava hazelnut jalapeno kale leek lentil lettuce lychee mustard nutmeg oatmeal okra olive omelet papaya parsley pickle pretzel prune pudding pumpkin quinoa radish raisin salsa sesame spinach squash syrup tamale tofu vanilla walnut yogurt zucchini dumpling'.split(/\s+/),
  nature: 'earth sun moon star cloud rain snow wind storm rainbow tree forest jungle leaf flower rose tulip grass mountain hill volcano river lake ocean sea wave beach sand island desert canyon cave rock stone crystal ice fire water sky sunset lightning thunder tornado hurricane glacier valley meadow garden planet comet meteor galaxy seed plant bush branch root log moss pine palm cactus aster birch blossom boulder breeze brook cedar cliff dune fern fjord frost glade gorge grove heather lagoon lilac lily mist oasis orchid peak pebble petal prairie reed ridge shrub spark summit swamp thicket thorn tide vista willow wood'.split(/\s+/),
  body: 'head face eye eyes ear nose mouth lip tooth tongue hair brain heart lung liver kidney bone skin blood arm hand finger thumb nail leg foot knee elbow shoulder neck back chest belly beard mustache eyebrow cheek chin forehead skull wrist ankle artery bladder digit flesh forearm gland gullet knuckle marrow organ pelvis pulse spleen stomach temple thigh torso waist throat muscle tonsil earlobe eyelash nostril molar biceps dimple freckle wrinkle tummy tendon reflex sneeze blink frown giggle laugh breath'.split(/\s+/),
  home: 'house home door window roof wall floor kitchen bedroom bathroom sofa couch chair table desk bed pillow blanket lamp light clock mirror rug carpet curtain shelf cabinet drawer fridge oven stove sink toilet shower towel soap brush broom bucket plate bowl cup glass spoon fork knife pan pot kettle jar bottle box basket key lock bell phone book magazine newspaper plant tv radio computer camera fan stairs balcony garden garage armchair basement bathtub candle cellar chandelier cupboard dish furnace hall hallway hamper heater laundry mantel mattress pantry patio radiator shutter teapot toaster trash vase wardrobe'.split(/\s+/),
  clothes: 'shirt pants jeans shorts dress skirt coat jacket sweater vest suit tie scarf hat cap glove mitten sock shoe boot sandal slipper belt button pocket zipper uniform pajama robe gown cloak cape mask crown ring necklace bracelet watch glasses sunglasses purse wallet backpack bag umbrella raincoat swimsuit apron beanie blazer blouse brooch buckle cardigan clogs fleece garter jumper kimono mittens necktie overalls parka poncho pumps shawl sleeve sneaker tights tunic gloves'.split(/\s+/),
  travel: 'car truck bus van taxi train plane boat ship ferry yacht canoe kayak rocket bicycle bike motorcycle scooter helicopter balloon jet submarine trolley wagon anchor compass map globe airport station road street highway bridge tunnel hotel ticket passport luggage suitcase backpack camera cruise island harbor port pier lighthouse journey tour trip voyage airplane avenue departure freeway lane motel railway resort subway terminal tourist tram flight caboose caravan carousel charter depot motorway seaport sidewalk steamer turnpike viaduct walkway waterway camping picnic landmark scenery skyline frontier customs baggage boarding runway hangar cockpit airship glider shuttle launch'.split(/\s+/),
  sports: 'football soccer basketball baseball tennis cricket golf hockey volleyball rugby boxing wrestling karate judo fencing archery skiing snowboard skating surfing swimming running jogging sprint marathon cycling gym workout yoga dancing chess trophy medal stadium arena referee player team coach champion winner race match game goal ball helmet bowling cheer diving gymnast javelin pitch rowing runner skate swimmer wrestler hurdle pushup situp squat barbell weights exercise training mascot huddle inning wicket pitcher catcher batter bowler goalie dribble block'.split(/\s+/),
  arts: 'music song sing dance guitar piano drum violin flute trumpet saxophone harp microphone concert band radio movie film painting paint brush canvas draw sketch art museum gallery statue sculpture theatre stage actor drama play comedy opera ballet poetry poem book novel writer author story fairy magic puppet mask costume clown magician rainbow cello chorus easel lyrics melody mime palette portrait rhythm sonnet theater painter singer tragedy verse stanza rhyme prose cartoon anime manga vinyl record banjo bugle cymbals kazoo mandolin maracas piccolo ukulele clarinet trombone viola perform producer director'.split(/\s+/),
  colors: 'black white red blue green yellow orange purple pink brown gray grey gold golden silver bronze coral ivory pearl ruby emerald sapphire amber jade olive lime navy teal maroon crimson violet magenta turquoise indigo beige cream tan peach mint sky ocean snow coal ash lemon plum berry rose sand flame blond charcoal lavender lilac mustard coffee ginger honey rainbow sunset sunrise burgundy chestnut cinnamon cobalt denim ebony fuchsia khaki mauve ochre platinum sepia sienna taupe topaz avocado'.split(/\s+/),
  people: 'man woman boy girl baby child adult friend family mother father sister brother son daughter grandma grandpa uncle aunt cousin wife husband bride groom king queen prince princess knight wizard witch fairy elf giant dwarf pirate cowboy clown robot alien ghost vampire zombie mermaid superhero doctor nurse teacher student police soldier sailor chef waiter cashier banker lawyer judge scientist engineer artist musician singer dancer actor athlete champion winner runner boxer ninja samurai hero villain monster angel devil acrobat astronaut babysitter barber blacksmith butcher butler carpenter clerk courier detective driver drummer fireman fisherman gardener guard hunter librarian lifeguard maid mayor mechanic miner monk nanny officer plumber postman priest professor reporter secretary shepherd surgeon tailor thief trader worker writer'.split(/\s+/),
  trade: 'truck money clock plane train envelope wheel camera harbor pilot captain mirror glass silver golden banker notebook diary tackle ferry yacht ship boat box package parcel letter mail stamp phone computer printer paper pen pencil folder briefcase suitcase wallet coin dollar bank store shop market factory office desk scale weight tag label receipt contract document key lock safe auction broker budget business cargo commerce credit currency customer dealer delivery deposit discount export finance freight goods import invoice merchant order payment purchase refund revenue salary sales shipment shipping supplier trade trader vendor yield'.split(/\s+/)
};

module.exports = PACKS;
