// ═══════════════════════════════════════════════════════════════════════
// clues.js — 20s hint clues for Champ Words
// Curated one-line clues per word + natural template fallbacks.
// Used by server.js sendWordHint() via generateClue(word, categoryId).
// ═══════════════════════════════════════════════════════════════════════

const CLUES = {
  // ── Animals ────────────────────────────────────────────────────────────
  ant: ['it works hard in a colony and carries tiny things'],
  ape: ['a big smart animal that can climb trees'],
  bat: ['a flying animal that comes out at night'],
  bear: ['a big furry animal that loves honey'],
  bee: ['it buzzes and makes honey'],
  bird: ['it has wings and can fly'],
  cat: ['a furry pet that says meow', 'a pet that chases mice'],
  cattle: ['farm animals that give milk'],
  chick: ['a baby bird', 'a baby chicken'],
  clam: ['a sea animal with a shell'],
  cod: ['a fish you can eat'],
  cow: ['a farm animal that gives milk'],
  crab: ['a sea animal that walks sideways'],
  crow: ['a black bird that says caw'],
  deer: ['a wild animal with antlers'],
  dog: ['a loyal pet that barks', 'a pet that wags its tail'],
  dove: ['a white bird, a symbol of peace'],
  duck: ['a water bird that quacks'],
  eagle: ['a big bird of prey', 'a bird that soars high'],
  eel: ['a long slippery fish'],
  emu: ['a tall bird that cannot fly'],
  fawn: ['a baby deer'],
  fish: ['an animal that lives in water'],
  flea: ['a tiny jumping bug'],
  fly: ['a small buzzing insect'],
  fox: ['a clever wild animal with a bushy tail'],
  frog: ['a green animal that hops and croaks'],
  gnat: ['a tiny flying bug'],
  goat: ['a farm animal that climbs hills'],
  hare: ['a fast animal like a big rabbit'],
  hawk: ['a bird of prey that hunts'],
  hen: ['a female chicken'],
  hog: ['a big pig'],
  horse: ['an animal you can ride', 'a farm animal that gallops'],
  insect: ['a small bug with six legs'],
  lamb: ['a baby sheep'],
  lark: ['a small singing bird'],
  lion: ['the king of the jungle', 'a big cat that roars'],
  mare: ['a female horse'],
  mice: ['small animals that squeak'],
  mole: ['a small animal that digs tunnels'],
  monkey: ['a playful animal that swings in trees'],
  moth: ['an insect attracted to light at night'],
  mouse: ['a tiny animal that likes cheese'],
  mule: ['an animal like a horse that carries loads'],
  owl: ['a night bird that says hoot'],
  ox: ['a strong farm animal'],
  pig: ['a farm animal that oinks', 'an animal that rolls in mud'],
  pony: ['a small horse'],
  pup: ['a baby dog'],
  ram: ['a male sheep with horns'],
  rat: ['a rodent that lives in the city'],
  robin: ['a small bird with a red chest'],
  seal: ['a sea animal that claps its flippers'],
  shark: ['a big fish with sharp teeth'],
  sheep: ['a fluffy farm animal that says baa'],
  snake: ['a long animal with no legs that hisses'],
  stag: ['a male deer'],
  swan: ['a beautiful white water bird'],
  tiger: ['a big striped cat'],
  toad: ['a bumpy animal that hops'],
  tuna: ['a big fish used in sushi'],
  wasp: ['a stinging insect, black and yellow'],
  wolf: ['a wild animal that howls at the moon'],
  worm: ['a long thin animal in the soil'],
  wren: ['a tiny brown singing bird'],
  yak: ['a hairy animal that lives in the mountains'],
  animal: ['a living creature that is not a plant'],
  dragon: ['a mythical creature that breathes fire'],

  // ── Food & drink ───────────────────────────────────────────────────────
  apple: ['a round fruit that can be red or green', 'a fruit that keeps the doctor away'],
  banana: ['a long yellow fruit'],
  bread: ['a bakery item you make toast from'],
  butter: ['a creamy spread made from milk'],
  cake: ['a sweet dessert you bake for birthdays'],
  candy: ['a sweet treat'],
  cherry: ['a small red fruit with a stone'],
  coffee: ['a hot drink that wakes you up'],
  corn: ['a yellow vegetable on a cob'],
  cream: ['the fatty part of milk, used in desserts'],
  egg: ['a breakfast item a hen lays'],
  garlic: ['a smelly white bulb used in cooking'],
  grape: ['a small fruit used to make wine'],
  ham: ['a sliced meat from a pig'],
  honey: ['a sweet golden syrup made by bees'],
  jam: ['a sweet spread made from fruit'],
  juice: ['a drink squeezed from fruit'],
  lemon: ['a sour yellow fruit'],
  lime: ['a small green sour fruit'],
  milk: ['a white drink from cows'],
  mint: ['a fresh green herb', 'a flavor in toothpaste'],
  nut: ['a crunchy snack inside a shell'],
  oat: ['a grain used for porridge'],
  oil: ['a liquid used for frying'],
  olive: ['a small green or black fruit, pressed for oil'],
  orange: ['a round fruit the same color as its name'],
  pasta: ['noodles you boil for dinner'],
  pea: ['a tiny round green vegetable'],
  peanut: ['a nut that grows underground, used for butter'],
  pear: ['a sweet fruit shaped like a bell'],
  pepper: ['a spicy vegetable, red or green'],
  pie: ['a baked dessert with a crust'],
  pizza: ['a round flat food with cheese on top'],
  plum: ['a purple fruit with a stone'],
  pork: ['meat from a pig'],
  potato: ['a starchy vegetable that makes fries'],
  rice: ['small white grains cooked with meals'],
  salad: ['a bowl of fresh vegetables'],
  salt: ['a white seasoning for food'],
  sauce: ['a liquid you pour over food'],
  snack: ['a small bite between meals'],
  soda: ['a fizzy drink'],
  soy: ['a bean used to make sauce and milk'],
  spice: ['something that adds flavor to food'],
  steak: ['a thick slice of grilled meat'],
  stew: ['a slow-cooked pot of meat and vegetables'],
  sugar: ['a sweet white powder'],
  sweet: ['something that tastes like sugar'],
  syrup: ['a thick sweet liquid for pancakes'],
  tea: ['a hot drink made from leaves'],
  toast: ['bread that is browned in a toaster'],
  water: ['the drink everyone needs'],
  wheat: ['a grain used to make flour'],
  wine: ['an alcoholic drink made from grapes'],
  yam: ['an orange root vegetable'],

  // ── Colors ─────────────────────────────────────────────────────────────
  black: ['the darkest color'],
  blue: ['the color of a clear sky'],
  bronze: ['a shiny brown metal color'],
  coral: ['a pink-orange color like a sea reef'],
  cream: ['a pale yellow-white color'],
  gold: ['a shiny yellow color like jewelry'],
  golden: ['the color of the sun'],
  gray: ['the color of a cloudy sky'],
  green: ['the color of grass and leaves'],
  grey: ['the color between black and white'],
  ivory: ['a creamy white color'],
  jade: ['a green color like a gemstone'],
  lime: ['a bright green-yellow color'],
  navy: ['a dark blue color'],
  olive: ['a green-brown color'],
  opal: ['a shimmering rainbow gem color'],
  pearl: ['a soft white color like jewelry'],
  pink: ['a light red color'],
  plum: ['a dark purple color'],
  red: ['the color of blood and roses'],
  rose: ['a soft pink color'],
  rosy: ['a warm pink color like cheeks'],
  ruby: ['a deep red color like a gem'],
  rust: ['a brown-orange color like old metal'],
  salmon: ['a pink-orange color like the fish'],
  sandy: ['a light brown color like a beach'],
  silver: ['a shiny gray color like metal'],
  tan: ['a light brown color'],
  yellow: ['the color of the sun and lemons'],

  // ── Nature ─────────────────────────────────────────────────────────────
  air: ['something you breathe'],
  ash: ['the gray powder left after a fire'],
  autumn: ['the season of falling leaves'],
  bay: ['a curved part of the coast'],
  beach: ['a sandy place by the sea'],
  breeze: ['a gentle wind'],
  bush: ['a small woody plant'],
  cave: ['a hollow space in a mountain'],
  clay: ['soft earth used to make pots'],
  cliff: ['a tall steep rock by the sea'],
  cloud: ['a fluffy white thing in the sky'],
  coast: ['the land next to the sea'],
  coral: ['a colorful reef creature'],
  dawn: ['the early morning when the sun rises'],
  desert: ['a dry sandy place with little rain'],
  dew: ['drops of water on grass in the morning'],
  dune: ['a hill of sand'],
  dusk: ['the time when the sun goes down'],
  earth: ['the planet we live on', 'the ground beneath your feet'],
  east: ['the direction the sun rises'],
  fern: ['a leafy green plant with no flowers'],
  field: ['a big open area of grass'],
  fire: ['hot flames that give light'],
  flame: ['the burning part of a fire'],
  fog: ['thick low cloud you can walk through'],
  forest: ['a big area full of trees'],
  frost: ['icy crystals on windows in winter'],
  gale: ['a very strong wind'],
  garden: ['a place where plants grow'],
  glen: ['a small valley'],
  grass: ['the green stuff on lawns'],
  grove: ['a small group of trees'],
  harbor: ['a safe place for boats'],
  haven: ['a peaceful safe place'],
  hill: ['a small mountain'],
  horizon: ['the line where sky meets land'],
  ice: ['frozen water'],
  island: ['land surrounded by water'],
  isle: ['a small island'],
  jungle: ['a thick tropical forest'],
  lake: ['a big area of water surrounded by land'],
  land: ['the ground, not water'],
  leaf: ['a green part of a plant'],
  light: ['what the sun gives us'],
  mist: ['thin fog'],
  moon: ['it shines at night', 'it orbits the earth'],
  moor: ['open wild land'],
  moss: ['a soft green plant on rocks'],
  mud: ['wet soft dirt'],
  north: ['the direction at the top of a compass'],
  ocean: ['a huge body of salt water'],
  orbit: ['the path a planet takes around the sun'],
  ozone: ['a gas layer high above the earth'],
  peak: ['the top of a mountain'],
  pine: ['a tall evergreen tree'],
  plain: ['flat open land'],
  planet: ['a world like Earth'],
  pond: ['a small lake'],
  rain: ['water falling from clouds', 'what makes the grass grow'],
  reef: ['a colorful underwater rock garden'],
  ridge: ['the top edge of a mountain'],
  river: ['water that flows to the sea'],
  rock: ['a hard stone'],
  rocky: ['covered in stones'],
  sand: ['tiny grains on a beach'],
  sandy: ['covered in tiny grains'],
  sea: ['a big body of salt water'],
  season: ['one of four parts of the year'],
  shadow: ['a dark shape made by light'],
  shore: ['the land at the edge of the sea'],
  sky: ['the blue space above us'],
  slope: ['a slanted hillside'],
  snow: ['frozen white flakes in winter'],
  soil: ['the earth plants grow in'],
  solar: ['to do with the sun'],
  south: ['the direction opposite north'],
  spring: ['the season of new flowers'],
  star: ['a twinkling light in the night sky'],
  stone: ['a small rock'],
  storm: ['it appears during heavy rain', 'it brings thunder, lightning and wind'],
  stream: ['a small fast river'],
  summer: ['the hottest season'],
  sun: ['the bright star in our sky'],
  sunny: ['a day with lots of sun'],
  surf: ['the waves of the sea'],
  swamp: ['wet muddy land'],
  tide: ['the rise and fall of the sea'],
  timber: ['wood used for building'],
  tree: ['a tall plant with a trunk'],
  valley: ['low land between mountains'],
  volcano: ['a mountain that erupts lava'],
  warmth: ['a gentle heat'],
  wave: ['a rolling crest on the sea'],
  weather: ['the rain, sun and wind outside'],
  west: ['the direction the sun sets'],
  wind: ['moving air you can feel'],
  winter: ['the coldest season'],
  wood: ['material from trees'],
  world: ['the planet and everything on it'],

  // ── Body ───────────────────────────────────────────────────────────────
  ankle: ['the joint between your foot and leg'],
  arm: ['the limb you wave with'],
  back: ['the part behind your chest'],
  beard: ["hair that grows on a man's chin"],
  blood: ['the red liquid inside you'],
  bone: ['the hard part inside your body'],
  brain: ['the organ that thinks'],
  breath: ['the air you take in and out'],
  cheek: ['the soft part of your face beside your nose'],
  chest: ['the front part of your upper body'],
  chin: ['the part below your mouth'],
  ear: ['the part you hear with'],
  eye: ['the part you see with'],
  face: ['the front of your head'],
  finger: ['a digit on your hand'],
  fist: ['a closed hand'],
  foot: ['the part you stand on'],
  hair: ['the strands on your head'],
  hand: ['the part you wave and grab with'],
  head: ['the top part of your body'],
  health: ['how well your body feels'],
  heart: ['the organ that pumps blood'],
  heel: ['the back of your foot'],
  hip: ['the joint between leg and body'],
  jaw: ['the bone that holds your teeth'],
  kidney: ['an organ that filters your blood'],
  knee: ['the joint in the middle of your leg'],
  leg: ['the limb you walk with'],
  limb: ['an arm or a leg'],
  lip: ['the soft edge of your mouth'],
  liver: ['a large organ inside you'],
  lung: ['the organ you breathe with'],
  mouth: ['the part you eat and talk with'],
  muscle: ['the tissue that moves your body'],
  nail: ['the hard cover on your fingertips'],
  nape: ['the back of your neck'],
  neck: ['the part between head and shoulders'],
  nerve: ['a pathway for messages in your body'],
  nose: ['the part you smell with'],
  palm: ['the inside of your hand'],
  rib: ['a curved bone around your chest'],
  shin: ['the front of your lower leg'],
  skull: ['the bone around your brain'],
  spine: ['the line of bones down your back'],
  thumb: ['the short thick finger'],
  tissue: ['the soft material inside your body'],
  toe: ['a digit on your foot'],
  tongue: ['the part in your mouth that tastes'],
  vein: ['a tube that carries blood'],
  waist: ['the middle part of your body'],
  wrist: ['the joint between hand and arm'],

  // ── Home & stuff ───────────────────────────────────────────────────────
  basin: ['a bowl-shaped sink for washing'],
  bath: ['a soak in the tub'],
  bed: ['where you sleep'],
  bedroom: ['the room where you sleep'],
  bench: ['a long seat'],
  bin: ['a container for rubbish'],
  blanket: ['what keeps you warm in bed'],
  bolt: ['a metal fastener'],
  book: ['something you read'],
  bottle: ['a container for drinks'],
  bowl: ['a round dish for soup'],
  box: ['a container with a lid'],
  brush: ['a tool with bristles'],
  bucket: ['a pail for carrying water'],
  cabinet: ['a cupboard with shelves'],
  candle: ['a wax stick with a flame'],
  carpet: ['a soft floor covering'],
  ceiling: ['the top surface of a room'],
  chain: ['metal links joined together'],
  chair: ['something you sit on'],
  chamber: ['a room'],
  chest: ['a big box with a lid'],
  clock: ['it tells the time'],
  cloth: ['a piece of fabric'],
  closet: ['a small room for storage'],
  couch: ['a soft sofa to sit on'],
  counter: ['a work surface in a kitchen'],
  cup: ['a small container for drinks'],
  cushion: ['a soft pad to sit on'],
  desk: ['a table for writing'],
  door: ['you open it to enter a room'],
  drawer: ['a sliding box in furniture'],
  fan: ['it blows air to cool you'],
  floor: ['the surface you walk on'],
  fridge: ['it keeps food cold'],
  glass: ['a container to drink from'],
  hammer: ['a tool for hitting nails'],
  handle: ['the part you grab to open'],
  house: ['a place where people live'],
  hut: ['a small simple house'],
  jar: ['a glass container with a lid'],
  jug: ['a container for pouring drinks'],
  key: ['it opens a lock'],
  kitchen: ['the room where food is cooked'],
  knife: ['a tool for cutting'],
  ladder: ['steps you climb up'],
  lamp: ['a light on a table'],
  lid: ['the top cover of a container'],
  lock: ['it keeps a door closed'],
  mat: ['a small floor rug'],
  mirror: ['you see yourself in it'],
  mop: ['a tool for cleaning floors'],
  mug: ['a big cup for hot drinks'],
  nail: ['a small metal spike for hammering'],
  oven: ['you bake in it'],
  pan: ['a frying vessel'],
  peg: ['a hook for hanging things'],
  pen: ['you write with it'],
  plate: ['a flat dish for food'],
  plug: ['it fits into a socket'],
  pocket: ['a pouch in clothing'],
  pot: ['a cooking vessel'],
  roof: ['the top of a house'],
  room: ['a space inside a house'],
  rug: ['a small carpet'],
  shelf: ['a flat board for storage'],
  sheet: ['bed linen'],
  shower: ['where you wash standing up'],
  sink: ['where you wash dishes'],
  sofa: ['a soft seat for a few people'],
  spoon: ['a tool for eating soup'],
  stair: ['a step to climb'],
  stove: ['a cooker'],
  table: ['a flat surface for meals'],
  tape: ['a sticky strip'],
  tent: ['a shelter for camping'],
  tile: ['a flat square covering'],
  tin: ['a metal container'],
  towel: ['you dry yourself with it'],
  tower: ['a tall narrow building'],
  tray: ['a flat holder for serving'],
  tub: ['a bath container'],
  vase: ['a jar for flowers'],
  wall: ['a side of a room'],
  window: ['you look through it'],
  wire: ['a metal thread for electricity'],
  wok: ['a round frying pan'],
  yard: ['the outdoor space around a house'],


  // ── Travel ──────────────────────────────────────────────────────────────
  airline: ['a company that flies planes'],
  auto: ['a car'],
  avenue: ['a wide street'],
  bike: ['a two-wheeled pedal vehicle'],
  boat: ['a vessel that floats on water'],
  bus: ['a big vehicle with many seats'],
  cab: ['a taxi'],
  car: ['a four-wheeled vehicle'],
  cart: ['a small vehicle pulled along'],
  drive: ['to steer a car'],
  driver: ['the person steering a vehicle'],
  ferry: ['a boat that carries people across water'],
  fleet: ['a group of ships or cars'],
  flight: ['a journey by plane'],
  fly: ['to travel through the air'],
  fuel: ['what makes engines run'],
  gear: ['the mechanics of a car'],
  highway: ['a big fast road'],
  jet: ['a fast plane'],
  lane: ['a narrow road'],
  motor: ['an engine'],
  plane: ['a flying vehicle with wings'],
  rail: ['the track a train runs on'],
  rental: ['a car you pay to borrow'],
  ride: ['a trip in a vehicle'],
  road: ['a path for vehicles'],
  route: ['the way to go somewhere'],
  sail: ['to move a boat with wind'],
  ship: ['a big boat'],
  street: ['a road in a town'],
  taxi: ['a car you hail and pay for'],
  tire: ['the rubber wheel covering'],
  tour: ['a trip to see places'],
  tourism: ['traveling for fun'],
  tourist: ['a person visiting a place'],
  tow: ['to pull a vehicle'],
  track: ['the rails for a train'],
  traffic: ['cars moving on roads'],
  trail: ['a path through nature'],
  train: ['a vehicle on rails'],
  travel: ['to go from place to place'],
  trip: ['a short journey'],
  truck: ['a big vehicle for cargo'],
  tube: ['the underground railway'],
  tunnel: ['a passage through a hill'],
  van: ['a vehicle for carrying things'],
  vehicle: ['anything that carries people'],
  wagon: ['a cart with wheels'],
  wheel: ['the round part that rolls'],
  yacht: ['a fancy boat'],

  // ── Sports & games ─────────────────────────────────────────────────────
  arena: ['a big place for games'],
  ball: ['a round thing you kick or throw'],
  base: ['the starting point in a race'],
  camp: ['an outdoor stay in tents'],
  chess: ['a board game with kings and queens'],
  club: ['a stick used in golf'],
  court: ['the area where tennis is played'],
  dart: ['a small missile thrown at a board'],
  derby: ['a famous horse race'],
  disc: ['a flying disc game'],
  dive: ['to jump headfirst into water'],
  dodge: ['to move quickly to avoid'],
  dunk: ['to slam a ball through a hoop'],
  fight: ['a contest with punches'],
  fitness: ['being in good shape'],
  flag: ['a colorful cloth symbol'],
  game: ['something you play to win'],
  golf: ['a sport with clubs and a small ball'],
  gym: ['a place to exercise'],
  hike: ['a long walk in nature'],
  jog: ['a slow run'],
  jump: ['to leap into the air'],
  kick: ['to strike with your foot'],
  kite: ['a toy that flies in the wind'],
  league: ['a group of teams'],
  match: ['a contest between players'],
  net: ['the mesh in tennis or football goals'],
  park: ['a green space to play'],
  play: ['to take part in a game'],
  polo: ['a sport on horseback'],
  race: ['a contest of speed'],
  rally: ['a long fast drive in tennis'],
  ring: ['the square where boxers fight'],
  row: ['to move a boat with oars'],
  rugby: ['a rough ball sport'],
  run: ['to move fast on foot'],
  runner: ['a person who runs'],
  running: ['moving fast on foot'],
  score: ['points in a game'],
  scout: ['an explorer of talent'],
  shoot: ['to aim and fire a ball'],
  skate: ['to glide on ice or wheels'],
  ski: ['to slide on snow'],
  spar: ['to practice boxing'],
  speed: ['how fast something moves'],
  spin: ['to turn around fast'],
  sport: ['a game you play to keep fit'],
  stadium: ['a big arena for matches'],
  swim: ['to move through water'],
  tackle: ['to stop a player in a game'],
  team: ['a group playing together'],
  tennis: ['a sport with rackets and a ball'],
  toss: ['to throw lightly'],
  trainer: ['a coach who trains athletes'],
  trek: ['a long hard walk'],
  trial: ['a test of skill'],
  trot: ['to run slowly'],
  walk: ['to move on foot'],
  walker: ['a person who walks'],
  win: ['to finish first'],
  winner: ['the person who wins'],
  yoga: ['stretching exercise for body and mind'],
  zoom: ['to move very fast'],

  // ── Music & arts ───────────────────────────────────────────────────────
  album: ['a collection of songs'],
  art: ['drawing, painting and creativity'],
  artist: ['a person who makes art'],
  band: ['a group of musicians'],
  bass: ['a deep musical sound'],
  beat: ['the rhythm of music'],
  camera: ['you take photos with it'],
  choir: ['a group of singers'],
  cinema: ['a place where movies are shown'],
  circus: ['a show with clowns and acrobats'],
  comedy: ['a funny show'],
  comic: ['a funny illustrated story'],
  concert: ['a live music show'],
  dance: ['moving to music'],
  diary: ['a book of personal daily notes'],
  drama: ['an emotional play or series'],
  drum: ['a percussion instrument you hit'],
  essay: ['a short piece of writing'],
  fable: ['a short story with a lesson'],
  fiction: ['stories that are imagined'],
  film: ['a movie'],
  guitar: ['a string instrument you strum'],
  harp: ['a tall string instrument you pluck'],
  jazz: ['a style of music with swing'],
  legend: ['a famous story from the past'],
  magic: ['tricks that seem impossible'],
  movie: ['a story on screen'],
  museum: ['a place showing art and history'],
  music: ['sounds that make a melody'],
  opera: ['a sung theatrical show'],
  paint: ['colored liquid for pictures'],
  painter: ['an artist who uses paint'],
  photo: ['a picture taken with a camera'],
  piano: ['a keyboard instrument'],
  picture: ['an image on a wall'],
  poem: ['a short piece of verse'],
  poetry: ['verse writing'],
  poet: ['a person who writes poems'],
  poster: ['a printed picture for a wall'],
  prose: ['ordinary written language'],
  radio: ['you listen to music on it'],
  rhythm: ['the beat of music'],
  scene: ['a part of a play or film'],
  script: ['the written words of a show'],
  show: ['a performance to watch'],
  sketch: ['a quick drawing'],
  song: ['music with words'],
  sound: ['what you hear'],
  speech: ['talking to an audience'],
  spell: ['magic words'],
  stage: ['where performers stand'],
  story: ['a tale told or written'],
  studio: ['a room for making art or music'],
  style: ['a particular look or way'],
  symbol: ['a sign that means something'],
  tempo: ['the speed of music'],
  theater: ['a place for plays'],
  theme: ['the main idea of a story'],
  title: ['the name of a book or song'],
  tone: ['the quality of a sound'],
  tune: ['a melody'],
  video: ['moving pictures you watch'],
  voice: ['the sound of your speaking'],
  write: ['to put words on paper'],
  writer: ['a person who writes'],
  writing: ['putting words on paper'],
  written: ['put in words on paper'],

  // ── People & jobs ──────────────────────────────────────────────────────
  actor: ['a person who performs in movies'],
  agent: ['a person who represents others'],
  author: ['a person who writes books'],
  banker: ['a person who works with money'],
  boss: ['the person in charge'],
  bride: ['a woman on her wedding day'],
  buyer: ['a person who purchases things'],
  captain: ['the leader of a ship or team'],
  chef: ['a person who cooks professionally'],
  chief: ['the head of a group'],
  child: ['a young person'],
  citizen: ['a member of a country'],
  clerk: ['an office worker'],
  coach: ['a person who trains a team'],
  cop: ['a police officer'],
  cousin: ['a relative, an uncle or aunt child'],
  crew: ['a group working together'],
  dad: ['your father'],
  doctor: ['a person who treats the sick'],
  emperor: ['a ruler of an empire'],
  farmer: ['a person who grows crops'],
  father: ['your dad'],
  friend: ['a person you like and trust'],
  girl: ['a young female'],
  god: ['a supreme being'],
  guard: ['a person who protects'],
  guest: ['a visitor in your home'],
  guide: ['a person who shows the way'],
  guru: ['a wise teacher'],
  guy: ['a man'],
  hero: ['a brave person'],
  host: ['a person who welcomes guests'],
  human: ['a person'],
  hunter: ['a person who hunts animals'],
  infant: ['a baby'],
  judge: ['a person who decides in court'],
  kid: ['a child'],
  king: ['a male ruler'],
  knight: ['a medieval warrior'],
  lady: ['a woman'],
  lawyer: ['a person who practices law'],
  leader: ['a person who leads'],
  lord: ['a noble man'],
  maid: ['a female servant'],
  major: ['a senior military officer'],
  manager: ['a person who runs things'],
  master: ['a person in charge, an expert'],
  mate: ['a friend or partner'],
  mayor: ['the head of a town'],
  member: ['a person in a group'],
  model: ['a person who poses for photos'],
  mom: ['your mother'],
  monk: ['a religious man living simply'],
  mother: ['your mom'],
  nurse: ['a person who cares for the sick'],
  officer: ['a person in uniform with authority'],
  owner: ['a person who owns something'],
  parent: ['a mother or father'],
  patron: ['a supporter of the arts'],
  people: ['many persons'],
  person: ['a human being'],
  pilot: ['a person who flies a plane'],
  police: ['officers who keep order'],
  pope: ['the head of the catholic church'],
  prince: ['the son of a king'],
  pupil: ['a student'],
  queen: ['a female ruler'],
  reader: ['a person who reads'],
  rider: ['a person on a horse or bike'],
  ruler: ['a person who governs'],
  saint: ['a very holy person'],
  senator: ['a member of the senate'],
  sheriff: ['a county law officer'],
  singer: ['a person who sings'],
  sir: ['a polite title for a man'],
  sister: ['a female sibling'],
  slave: ['an enslaved person'],
  soldier: ['a person in an army'],
  son: ['a male child'],
  speaker: ['a person who talks publicly'],
  student: ['a person who learns'],
  teacher: ['a person who teaches'],
  tenant: ['a person who rents a home'],
  thief: ['a person who steals'],
  tribe: ['a group of people with shared culture'],
  uncle: ["your parent's brother"],
  veteran: ['a former soldier'],
  vet: ['a doctor for animals'],
  visitor: ['a person who comes to see'],
  voter: ['a person who votes'],
  widow: ['a woman whose husband has died'],
  wife: ['a married woman'],
  woman: ['an adult female'],
  worker: ['a person who works'],
  youth: ['a young person'],

  // ── Everyday words (mixed picks) ───────────────────────────────────────
  city: ['a big town'],
  day: ['24 hours'],
  home: ['where you live'],
  hour: ['sixty minutes'],
  love: ['a deep feeling of affection'],
  money: ['what you pay with'],
  month: ['about 30 days'],
  night: ['the dark part of the day'],
  school: ['where students learn'],
  time: ['what a clock measures'],
  week: ['seven days'],
  year: ['twelve months']
};

const CATEGORY_NOUNS = {
  animals: 'animal', food: 'food', nature: 'nature', body: 'body part',
  home: 'household thing', clothes: 'clothing', travel: 'travel thing',
  sports: 'sport or game', arts: 'music or art', colors: 'color',
  people: 'person or job', mixed: 'word'
};

const CATEGORY_PLACES = {
  animals: 'in nature or on a farm', food: 'in a kitchen or at a meal',
  nature: 'outdoors', body: 'on your body', home: 'around the house',
  clothes: 'in a wardrobe', travel: 'on a trip', sports: 'at a game',
  arts: 'in music or art', colors: 'in a rainbow', people: 'in a crowd',
  mixed: 'in everyday life'
};

// Return a one-line clue for the 20s hint: curated if available, else a template
function generateClue(word, categoryId, templateOnly) {
  const curated = CLUES[word];
  if (!templateOnly && curated && curated.length) {
    return curated[Math.floor(Math.random() * curated.length)];
  }
  const cat = CATEGORY_NOUNS[categoryId] || 'word';
  const place = CATEGORY_PLACES[categoryId] || 'in everyday life';
  const n = word.length;
  const first = word[0].toUpperCase();
  const last = word[word.length - 1].toUpperCase();
  const templates = [
    `It starts with '${first}' and has ${n} letters`,
    `It's a ${n}-letter ${cat} that starts with '${first}'`,
    `Think of a ${cat} you'd find ${place}`,
    `It ends with '${last}' and it's a ${cat}`,
    `It's a ${cat} — ${n} letters, starts with '${first}'`
  ];
  return templates[Math.floor(Math.random() * templates.length)];
}

module.exports = { CLUES, generateClue };
